logging:
    level:
        root: DEBUG
server:
    servlet:
        context-path: /demo
    port: 8443
    ssl:
        key-store: classpath:springboot.p12
        key-store-password: password
        key-store-type: pkcs12
        key-alias: springboot
        key-password: password
spring:
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ***
                        client-secret: ***
                    facebook:
                        client-id: ***
                        client-secret: ***
#                    cognito:
#                        client-id:
#                        client-secret:
